### ISSUE TITLE
[BUG] vercel 部署v2分支错误：

### ISSUE THREAD

**Issue by gd1214b** [RiverTwilight/YgkTool#40]
Cloning github.com/gd1214b/YgkTool (Branch: v2, Commit: c46f2c1)
--
18:09:25.096 | Cloning completed: 642.234ms
18:09:25.153 | Analyzing source code...
18:09:25.242 | Installing build runtime...
18:09:27.805 | Build runtime installed: 2.562s
18:09:28.709 | No Build Cache available
18:09:28.852 | Detected package.json
18:09:28.852 | Installing dependencies...
18:09:28.862 | Detected `package-lock.json` generated by npm 7...
18:09:44.010 | npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
18:09:44.607 | npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
18:09:46.113 | npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
18:09:46.353 | npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
18:09:49.735 | npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
18:09:56.522 | npm WARN deprecated @types/clipboard@2.0.7: This is a stub types definition. clipboard provides its own type definitions, so you do not need this installed.
18:09:59.462 | npm WARN deprecated querystring@0.2.0: The
18:09:59.538 | npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
18:09:59.826 | npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
18:09:59.974 | npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 \|\| >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
18:10:00.171 | npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 \|\| >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
18:10:03.696 | npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 \|\| >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
18:10:07.621 |  
18:10:07.621 | added 1539 packages in 39s
18:10:07.622 |  
18:10:07.622 | 84 packages are looking for funding
18:10:07.622 | run `npm fund` for details
18:10:07.859 | Detected `package-lock.json` generated by npm 7...
18:10:07.859 | Running "npm run build"
18:10:08.160 |  
18:10:08.160 | > ygktool@2.0.0 build
18:10:08.160 | > next build
18:10:08.161 |  
18:10:08.638 | info  - Loaded env from /vercel/path0/.env
18:10:09.372 | Attention: Next.js now collects completely anonymous telemetry regarding usage.
18:10:09.373 | This information is used to shape Next.js' roadmap and prioritize features.
18:10:09.373 | You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
18:10:09.373 | https://nextjs.org/telemetry
18:10:09.373 |  
18:10:09.424 | info  - Skipping validation of types...
18:10:09.762 | warn  - No ESLint configuration detected. Run next lint to begin setup
18:10:09.771 | info  - Creating an optimized production build...
18:10:09.820 | > [PWA] Compile client (static)
18:10:09.821 | > [PWA] Auto register service worker with: /vercel/path0/node_modules/next-pwa/register.js
18:10:09.821 | > [PWA] Service worker: /vercel/path0/public/sw.js
18:10:09.821 | > [PWA]   url: /sw.js
18:10:09.821 | > [PWA]   scope: /
18:10:10.038 | > [PWA] Compile server
18:10:36.835 | info  - Compiled successfully
18:10:36.836 | info  - Collecting page data...
18:10:39.406 | info  - Generating static pages (0/21)
18:10:39.554 | {
18:10:39.554 | name: '日期&时间计算',
18:10:39.555 | link: 'date_calculator',
18:10:39.555 | icon: '/icon/Google_Calendar_icon_(2020).svg',
18:10:39.555 | help: '输入负数可以向前推算',
18:10:39.556 | description: '计算两个日期间隔的天数和时间，或推算几天前后是哪一天，可以算算你活了多久 :)',
18:10:39.556 | channel: 4
18:10:39.556 | }
18:10:39.556 | {
18:10:39.557 | name: '番茄钟',
18:10:39.557 | link: 'pomodoro',
18:10:39.557 | icon: '/icon/pomodoro.png',
18:10:39.557 | description: '番茄工作法极大地提高了工作的效率，还会有意想不到的成就感。',
18:10:39.557 | channel: 4
18:10:39.557 | }
18:10:39.561 | {
18:10:39.562 | name: '樱花动漫视频解析',
18:10:39.562 | link: 'imomoe_parse',
18:10:39.562 | icon: '/icon/video.svg',
18:10:39.562 | help: '部分番剧无法解析（因为是流视频）',
18:10:39.562 | channel: 2,
18:10:39.563 | network: true
18:10:39.563 | }
18:10:39.603 | {
18:10:39.603 | name: 'JS键盘码查询',
18:10:39.603 | link: 'js_keycode',
18:10:39.603 | icon: '/icon/code-js-yellow/icon-192-maskable.png',
18:10:39.604 | channel: 3
18:10:39.604 | }
18:10:39.622 | {
18:10:39.623 | name: '词典',
18:10:39.623 | link: 'dic_ci',
18:10:39.623 | icon: '/icon/book.png',
18:10:39.623 | description: '便捷查询常用词',
18:10:39.623 | channel: 4,
18:10:39.623 | network: true
18:10:39.623 | }
18:10:39.636 | {
18:10:39.637 | name: '成语词典',
18:10:39.637 | link: 'dic_idiom',
18:10:39.637 | icon: '/icon/book.png',
18:10:39.637 | help: '支持缩写哦',
18:10:39.637 | channel: 4,
18:10:39.638 | network: true
18:10:39.638 | }
18:10:39.642 | info  - Generating static pages (5/21)
18:10:39.643 | {
18:10:39.643 | name: '文件树生成',
18:10:39.643 | link: 'folder_tree',
18:10:39.644 | icon: '/icon/file.jpg',
18:10:39.644 | description: '生成文件夹结构',
18:10:39.644 | help: '不支持移动端使用；文件数量过多可能会有卡顿',
18:10:39.644 | channel: 3
18:10:39.645 | }
18:10:39.661 | {
18:10:39.661 | name: '二维码生成',
18:10:39.661 | link: 'qrcode',
18:10:39.662 | icon: '/icon/qrcode.png',
18:10:39.662 | help: '',
18:10:39.662 | description: '支持自定义颜色和大小；支持生成WiFi码',
18:10:39.662 | channel: 2
18:10:39.662 | }
18:10:39.663 | {
18:10:39.664 | name: '化学方程式配平',
18:10:39.664 | link: 'cem',
18:10:39.664 | icon: '/icon/magic-line-blue/icon-192-maskable.png',
18:10:39.664 | channel: 4
18:10:39.664 | }
18:10:39.679 | {
18:10:39.679 | name: 'MIME-type查询',
18:10:39.679 | link: 'mimetype',
18:10:39.679 | icon: '/icon/file_present-green/icon-192-maskable.png',
18:10:39.679 | description: '查询文件的MIME-type，支持正反查询',
18:10:39.680 | channel: 3
18:10:39.680 | }
18:10:39.695 | {
18:10:39.695 | name: 'HTML转JSX',
18:10:39.695 | link: 'html2jsx',
18:10:39.695 | icon: '/icon/code-html-green/icon-192-maskable.png',
18:10:39.695 | help: '不支持部分Html属性，请手动改为小驼峰命名法，所有操作均在本地执行，不消耗数据流量',
18:10:39.695 | channel: 3
18:10:39.695 | }
18:10:39.697 | info  - Generating static pages (10/21)
18:10:39.698 | {
18:10:39.698 | name: 'PornHub风格Logo生成',
18:10:39.698 | link: 'fake_pornhub_logo',
18:10:39.699 | icon: '/icon/imagesearch_roller-orange/icon-192-maskable.png',
18:10:39.699 | help: '仅供娱乐，产生任何后果自负',
18:10:39.699 | channel: 2
18:10:39.699 | }
18:10:39.831 | info  - Generating static pages (15/21)
18:10:40.166 | info  - Generating static pages (21/21)
18:10:40.181 | info  - Finalizing page optimization...
18:10:40.193 |  
18:10:40.202 | Page                                       Size     First Load JS
18:10:40.202 | ┌ ● /                                      46.7 kB         264 kB
18:10:40.203 | ├   /_app                                  0 B             167 kB
18:10:40.203 | ├ ○ /404                                   2.38 kB         169 kB
18:10:40.203 | ├ ● /about                                 1.72 kB         202 kB
18:10:40.203 | ├ λ /api/sendToTelegram                    0 B             167 kB
18:10:40.203 | ├ ● /app/[id] (761 ms)                     7.43 kB         225 kB
18:10:40.203 | ├   ├ /zh-CN/app/date_calculator
18:10:40.203 | ├   ├ /zh-CN/app/pomodoro
18:10:40.203 | ├   ├ /zh-CN/app/imomoe_parse
18:10:40.203 | ├   └ [+9 more paths]
18:10:40.203 | ├ ● /discover                              314 B           167 kB
18:10:40.203 | ├ ● /feedback                              2.13 kB         186 kB
18:10:40.203 | └ ● /terms                                 1.05 kB         201 kB
18:10:40.203 | + First Load JS shared by all              167 kB
18:10:40.203 | ├ chunks/framework-8957c350a55da097.js   42.2 kB
18:10:40.203 | ├ chunks/main-b40209780bd21505.js        29.6 kB
18:10:40.204 | ├ chunks/pages/_app-53b6891880df8b47.js  93 kB
18:10:40.204 | ├ chunks/webpack-e4b6d5375a85a4de.js     1.9 kB
18:10:40.204 | └ css/17b258f1edc72a82.css               216 B
18:10:40.204 |  
18:10:40.204 | λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
18:10:40.204 | ○  (Static)  automatically rendered as static HTML (uses no initial props)
18:10:40.204 | ●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
18:10:40.204 |  
18:10:40.344 | Error: No Output Directory named "build" found after the Build completed. You can configure the Output Directory in your Project Settings. Learn More: https://vercel.link/missing-public-directory

**Comment by RiverTwilight** [comment]
请在 vercel 中重新建立项目，并且选择”next"框架，vercel 会自动识别输出目录。

确保部署设置与下图一致。

![image](https://user-images.githubusercontent.com/52880665/211447656-f60261a6-b761-47e7-bd17-269d0fb4a73a.png)
