### ISSUE TITLE
[BUG] 收藏标题遮挡边框

### ISSUE THREAD

**Issue by Jesse205** [RiverTwilight/YgkTool#72]
![Screenshot_2023-06-11-16-59-02-421_com.hicloud.browser.jpg](https://github.com/RiverTwilight/YgkTool/assets/51242302/43ecbdd4-e108-40ff-ba15-84b342f7edf9)
收藏标题遮挡边框，不美观

**Comment by RiverTwilight** [comment]
Thanks for your feedback. We have fixed the problem now.
